
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `autoDB`.`VEHICLE`;
DROP TABLE IF EXISTS `autoDB`.`MODEL`;
DROP TABLE IF EXISTS `autoDB`.`MAKE`;
DROP TABLE IF EXISTS `autoDB`.`OWNER`;
DROP TABLE IF EXISTS `autoDB`.`USER_ROLE` ;
DROP TABLE IF EXISTS `autoDB`.`APP_USER` ;
DROP TABLE IF EXISTS `autoDB`.`ROLE` ;
DROP TABLE IF EXISTS `autoDB`.`USERS` ;
DROP TABLE IF EXISTS `autoDB`.`ADDRESS` ;
DROP TABLE IF EXISTS `autoDB`.`REGION` ;
DROP TABLE IF EXISTS `autoDB`.`COUNTRY` ;
DROP TABLE IF EXISTS `autoDB`.`USTATUS` ;
DROP TABLE IF EXISTS `autoDB`.`SSTATUS` ;
DROP TABLE IF EXISTS `autoDB`.`BODYTYPE` ;
DROP TABLE IF EXISTS `autoDB`.`CATEGORY` ;
DROP TABLE IF EXISTS `autoDB`.`ENGINE` ;
DROP TABLE IF EXISTS `autoDB`.`PARTS` ;
DROP TABLE IF EXISTS `autoDB`.`WORK` ;
DROP TABLE IF EXISTS `autoDB`.`TRIM` ;
DROP TABLE IF EXISTS `autoDB`.`SOURCE` ;
DROP TABLE IF EXISTS `autoDB`.`SERVICEORDER` ;
DROP TABLE IF EXISTS `autoDB`.`INVENTORY_SOURCE` ;
DROP TABLE IF EXISTS `autoDB`.`INVENTORY` ;

SET FOREIGN_KEY_CHECKS = 1;
