
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `autoDB`.`VEHICLE`;
DROP TABLE IF EXISTS `autoDB`.`MODEL`;
DROP TABLE IF EXISTS `autoDB`.`MAKE`;
DROP TABLE IF EXISTS `autoDB`.`OWNER`;
DROP TABLE IF EXISTS `autoDB`.`USER_ROLE` ;
DROP TABLE IF EXISTS `autoDB`.`APP_USER` ;
DROP TABLE IF EXISTS `autoDB`.`ROLE` ;
DROP TABLE IF EXISTS `autoDB`.`USERS` ;
DROP TABLE IF EXISTS `autoDB`.`ADDRESS` ;
DROP TABLE IF EXISTS `autoDB`.`REGION` ;
DROP TABLE IF EXISTS `autoDB`.`COUNTRY` ;
DROP TABLE IF EXISTS `autoDB`.`USTATUS` ;
DROP TABLE IF EXISTS `autoDB`.`SSTATUS` ;
DROP TABLE IF EXISTS `autoDB`.`CATEGORY` ;
DROP TABLE IF EXISTS `autoDB`.`PARTS` ;
DROP TABLE IF EXISTS `autoDB`.`WORK` ;
DROP TABLE IF EXISTS `autoDB`.`SOURCE` ;
DROP TABLE IF EXISTS `autoDB`.`SERVICEORDER` ;
DROP TABLE IF EXISTS `autoDB`.`INVENTORY_SOURCE` ;
DROP TABLE IF EXISTS `autoDB`.`INVENTORY` ;

DROP TABLE IF EXISTS `autoDB`.`COLOURS` ;
DROP TABLE IF EXISTS `autoDB`.`DRIVETYPE` ;
DROP TABLE IF EXISTS `autoDB`.`EBUILDS` ;
DROP TABLE IF EXISTS `autoDB`.`ECONFIG` ;
DROP TABLE IF EXISTS `autoDB`.`ENGINE` ;
DROP TABLE IF EXISTS `autoDB`.`TRIMs` ;
DROP TABLE IF EXISTS `autoDB`.`TRIM` ;
DROP TABLE IF EXISTS `autoDB`.`FUELS` ;
DROP TABLE IF EXISTS `autoDB`.`BODYTYPE` ;
DROP TABLE IF EXISTS `autoDB`.`INSIGNIA` ;
DROP TABLE IF EXISTS `autoDB`.`MODELS`;
DROP TABLE IF EXISTS `autoDB`.`MSR`;
DROP TABLE IF EXISTS `autoDB`.`MODEL`;
DROP TABLE IF EXISTS `autoDB`.`TRIMNAME`;

SET FOREIGN_KEY_CHECKS = 1;
